// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RS1_2024_25.API.Data;

#nullable disable

namespace RS1_2024_25.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241202135111_UpdateDataSeed")]
    partial class UpdateDataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Auth.MyAppUser", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsManager")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("MyAppUsers");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Auth.MyAuthenticationToken", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MyAppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("MyAppUserId");

                    b.ToTable("MyAuthenticationTokens");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("CarId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            CarId = 1,
                            Brand = "Volkswagen",
                            Model = "Golf",
                            Type = "Hatchback",
                            Year = 2022
                        },
                        new
                        {
                            CarId = 2,
                            Brand = "Audi",
                            Model = "Q5",
                            Type = "SUV",
                            Year = 2021
                        },
                        new
                        {
                            CarId = 3,
                            Brand = "Renault",
                            Model = "Clio",
                            Type = "Hatchback",
                            Year = 2023
                        },
                        new
                        {
                            CarId = 4,
                            Brand = "Peugeot",
                            Model = "508",
                            Type = "Sedan",
                            Year = 2020
                        },
                        new
                        {
                            CarId = 5,
                            Brand = "Fiat",
                            Model = "Panda",
                            Type = "Compact",
                            Year = 2019
                        });
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.CarEngine", b =>
                {
                    b.Property<int>("CarEngineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarEngineId"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("EngineId")
                        .HasColumnType("int");

                    b.HasKey("CarEngineId");

                    b.HasIndex("CarId");

                    b.HasIndex("EngineId");

                    b.ToTable("CarEngines");

                    b.HasData(
                        new
                        {
                            CarEngineId = 1,
                            CarId = 1,
                            EngineId = 1
                        },
                        new
                        {
                            CarEngineId = 2,
                            CarId = 2,
                            EngineId = 2
                        },
                        new
                        {
                            CarEngineId = 3,
                            CarId = 3,
                            EngineId = 3
                        },
                        new
                        {
                            CarEngineId = 4,
                            CarId = 4,
                            EngineId = 4
                        },
                        new
                        {
                            CarEngineId = 5,
                            CarId = 5,
                            EngineId = 5
                        });
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Brakes"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Suspension"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Engine Parts"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Exhaust Systems"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Oil and Fluids"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Filters"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Electrical Components"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Cooling Systems"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Interior Accessories"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Tires and Wheels"
                        });
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.City", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CountryId = 1,
                            Name = "Banja Luka"
                        },
                        new
                        {
                            ID = 2,
                            CountryId = 1,
                            Name = "Bihać"
                        },
                        new
                        {
                            ID = 3,
                            CountryId = 1,
                            Name = "Bijeljina"
                        },
                        new
                        {
                            ID = 4,
                            CountryId = 1,
                            Name = "Bosanska Krupa"
                        },
                        new
                        {
                            ID = 5,
                            CountryId = 1,
                            Name = "Cazin"
                        },
                        new
                        {
                            ID = 6,
                            CountryId = 1,
                            Name = "Čapljina"
                        },
                        new
                        {
                            ID = 7,
                            CountryId = 1,
                            Name = "Drventa"
                        },
                        new
                        {
                            ID = 8,
                            CountryId = 1,
                            Name = "Doboj"
                        },
                        new
                        {
                            ID = 9,
                            CountryId = 1,
                            Name = "Goražde"
                        },
                        new
                        {
                            ID = 10,
                            CountryId = 1,
                            Name = "Gračanica"
                        },
                        new
                        {
                            ID = 11,
                            CountryId = 1,
                            Name = "Cityačac"
                        },
                        new
                        {
                            ID = 12,
                            CountryId = 1,
                            Name = "Cityiška"
                        },
                        new
                        {
                            ID = 13,
                            CountryId = 1,
                            Name = "Konjic"
                        },
                        new
                        {
                            ID = 14,
                            CountryId = 1,
                            Name = "Laktaši"
                        },
                        new
                        {
                            ID = 15,
                            CountryId = 1,
                            Name = "Livno"
                        },
                        new
                        {
                            ID = 16,
                            CountryId = 1,
                            Name = "Lukavac"
                        },
                        new
                        {
                            ID = 17,
                            CountryId = 1,
                            Name = "Ljubuški"
                        },
                        new
                        {
                            ID = 18,
                            CountryId = 1,
                            Name = "Mostar"
                        },
                        new
                        {
                            ID = 19,
                            CountryId = 1,
                            Name = "Orašje"
                        },
                        new
                        {
                            ID = 20,
                            CountryId = 1,
                            Name = "Prijedor"
                        },
                        new
                        {
                            ID = 21,
                            CountryId = 1,
                            Name = "Prnjavor"
                        },
                        new
                        {
                            ID = 22,
                            CountryId = 1,
                            Name = "Sarajevo"
                        },
                        new
                        {
                            ID = 23,
                            CountryId = 1,
                            Name = "Srebrenik"
                        },
                        new
                        {
                            ID = 24,
                            CountryId = 1,
                            Name = "Stolac"
                        },
                        new
                        {
                            ID = 25,
                            CountryId = 1,
                            Name = "Široki Brijeg"
                        },
                        new
                        {
                            ID = 26,
                            CountryId = 1,
                            Name = "Travnik"
                        },
                        new
                        {
                            ID = 27,
                            CountryId = 1,
                            Name = "Tuzla"
                        },
                        new
                        {
                            ID = 28,
                            CountryId = 1,
                            Name = "Visoko"
                        },
                        new
                        {
                            ID = 29,
                            CountryId = 1,
                            Name = "Zavidovići"
                        },
                        new
                        {
                            ID = 30,
                            CountryId = 1,
                            Name = "Zenica"
                        },
                        new
                        {
                            ID = 31,
                            CountryId = 1,
                            Name = "Zvornik"
                        },
                        new
                        {
                            ID = 32,
                            CountryId = 1,
                            Name = "Živinice"
                        },
                        new
                        {
                            ID = 33,
                            CountryId = 1,
                            Name = "Donji Vakuf"
                        },
                        new
                        {
                            ID = 34,
                            CountryId = 1,
                            Name = "Zavidovići"
                        });
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Country", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Bosna i Hercegovina"
                        });
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Engine", b =>
                {
                    b.Property<int>("EngineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EngineId"));

                    b.Property<double>("Displacement")
                        .HasColumnType("float");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.HasKey("EngineId");

                    b.ToTable("Engines");

                    b.HasData(
                        new
                        {
                            EngineId = 1,
                            Displacement = 2000.0,
                            FuelType = "Diesel",
                            Name = "TDI 2.0",
                            Power = 150
                        },
                        new
                        {
                            EngineId = 2,
                            Displacement = 1500.0,
                            FuelType = "Petrol",
                            Name = "TSI 1.5",
                            Power = 130
                        },
                        new
                        {
                            EngineId = 3,
                            Displacement = 0.0,
                            FuelType = "Electric",
                            Name = "Electric R100",
                            Power = 100
                        },
                        new
                        {
                            EngineId = 4,
                            Displacement = 1600.0,
                            FuelType = "Hybrid",
                            Name = "HY 1.6",
                            Power = 180
                        },
                        new
                        {
                            EngineId = 5,
                            Displacement = 1200.0,
                            FuelType = "Petrol",
                            Name = "FIAT Petrol 1.2",
                            Power = 90
                        });
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.FAQ", b =>
                {
                    b.Property<int>("FAQId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FAQId"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FAQId");

                    b.HasIndex("UserId");

                    b.ToTable("FAQs");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Gender", b =>
                {
                    b.Property<int>("GenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenderId"));

                    b.Property<string>("GenderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenderId");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            GenderId = 1,
                            GenderName = "Male"
                        },
                        new
                        {
                            GenderId = 2,
                            GenderName = "Female"
                        });
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Journey", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("EndCityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartCityId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("EndCityId");

                    b.HasIndex("StartCityId");

                    b.ToTable("Journeys");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Manufacturer", b =>
                {
                    b.Property<int>("ManufacturerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManufacturerId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ManufacturerId");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            ManufacturerId = 1,
                            Address = "Džemala Bijedića 185, Sarajevo, Bosna i Hercegovina",
                            Contact = "+387 33 770 100",
                            Name = "Bosch"
                        },
                        new
                        {
                            ManufacturerId = 2,
                            Address = "Karađorđeva 120, Banja Luka, Bosna i Hercegovina",
                            Contact = "+387 51 210 990",
                            Name = "Valeo"
                        },
                        new
                        {
                            ManufacturerId = 3,
                            Address = "Rudarska 33, Tuzla, Bosna i Hercegovina",
                            Contact = "+387 35 320 870",
                            Name = "Delphi Technologies"
                        },
                        new
                        {
                            ManufacturerId = 4,
                            Address = "Bišće polje bb, Mostar, Bosna i Hercegovina",
                            Contact = "+387 36 576 600",
                            Name = "Continental"
                        },
                        new
                        {
                            ManufacturerId = 5,
                            Address = "Industrijska zona bb, Zenica, Bosna i Hercegovina",
                            Contact = "+387 32 450 110",
                            Name = "Magneti Marelli"
                        },
                        new
                        {
                            ManufacturerId = 6,
                            Address = "Pofalići bb, Sarajevo, Bosna i Hercegovina",
                            Contact = "+387 33 210 320",
                            Name = "Brembo"
                        },
                        new
                        {
                            ManufacturerId = 7,
                            Address = "Aleja Svetog Save 15, Banja Luka, Bosna i Hercegovina",
                            Contact = "+387 51 321 480",
                            Name = "TRW Automotive"
                        },
                        new
                        {
                            ManufacturerId = 8,
                            Address = "Zmaja od Bosne bb, Sarajevo, Bosna i Hercegovina",
                            Contact = "+387 33 234 567",
                            Name = "ATE"
                        });
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("StatusId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PartId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Part", b =>
                {
                    b.Property<int>("PartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartId"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("PartId");

                    b.HasIndex("CarId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Parts");

                    b.HasData(
                        new
                        {
                            PartId = 1,
                            CarId = 1,
                            CategoryId = 1,
                            Description = "High-quality brake pads for Golf",
                            ManufacturerId = 1,
                            Name = "Brake Pads",
                            Price = 0.0
                        },
                        new
                        {
                            PartId = 2,
                            CarId = 2,
                            CategoryId = 2,
                            Description = "Durable suspension springs for Q5",
                            ManufacturerId = 2,
                            Name = "Suspension Springs",
                            Price = 0.0
                        },
                        new
                        {
                            PartId = 3,
                            CarId = 3,
                            CategoryId = 6,
                            Description = "Oil filter suitable for Clio engines",
                            ManufacturerId = 3,
                            Name = "Engine Oil Filter",
                            Price = 0.0
                        },
                        new
                        {
                            PartId = 4,
                            CarId = 4,
                            CategoryId = 4,
                            Description = "Rust-resistant exhaust pipe for 508",
                            ManufacturerId = 4,
                            Name = "Exhaust Pipe",
                            Price = 0.0
                        },
                        new
                        {
                            PartId = 5,
                            CarId = 5,
                            CategoryId = 8,
                            Description = "High-performance coolant hose for Panda",
                            ManufacturerId = 5,
                            Name = "Coolant Hose",
                            Price = 0.0
                        },
                        new
                        {
                            PartId = 6,
                            CarId = 1,
                            CategoryId = 6,
                            Description = "Improves air intake efficiency for Golf",
                            ManufacturerId = 6,
                            Name = "Air Filter",
                            Price = 0.0
                        },
                        new
                        {
                            PartId = 7,
                            CarId = 2,
                            CategoryId = 2,
                            Description = "Enhanced suspension system for Q5",
                            ManufacturerId = 7,
                            Name = "Shock Absorber",
                            Price = 0.0
                        },
                        new
                        {
                            PartId = 8,
                            CarId = 3,
                            CategoryId = 7,
                            Description = "High-performance spark plugs for Clio",
                            ManufacturerId = 8,
                            Name = "Spark Plugs",
                            Price = 0.0
                        },
                        new
                        {
                            PartId = 9,
                            CarId = 4,
                            CategoryId = 4,
                            Description = "Eco-friendly exhaust component for 508",
                            ManufacturerId = 1,
                            Name = "Catalytic Converter",
                            Price = 0.0
                        },
                        new
                        {
                            PartId = 10,
                            CarId = 5,
                            CategoryId = 5,
                            Description = "Premium oil for Panda engines",
                            ManufacturerId = 2,
                            Name = "Engine Oil",
                            Price = 0.0
                        },
                        new
                        {
                            PartId = 11,
                            CarId = 1,
                            CategoryId = 1,
                            Description = "Front brake discs for Golf",
                            ManufacturerId = 3,
                            Name = "Brake Discs",
                            Price = 0.0
                        },
                        new
                        {
                            PartId = 12,
                            CarId = 2,
                            CategoryId = 2,
                            Description = "Steering system component for Q5",
                            ManufacturerId = 4,
                            Name = "Tie Rod Ends",
                            Price = 0.0
                        },
                        new
                        {
                            PartId = 13,
                            CarId = 3,
                            CategoryId = 3,
                            Description = "Efficient fuel pump for Clio",
                            ManufacturerId = 5,
                            Name = "Fuel Pump",
                            Price = 0.0
                        },
                        new
                        {
                            PartId = 14,
                            CarId = 4,
                            CategoryId = 3,
                            Description = "Boost engine power for 508",
                            ManufacturerId = 6,
                            Name = "Turbocharger",
                            Price = 0.0
                        },
                        new
                        {
                            PartId = 15,
                            CarId = 5,
                            CategoryId = 9,
                            Description = "All-weather wipers for Panda",
                            ManufacturerId = 7,
                            Name = "Windshield Wipers",
                            Price = 0.0
                        },
                        new
                        {
                            PartId = 16,
                            CarId = 1,
                            CategoryId = 8,
                            Description = "High-efficiency radiator for Golf",
                            ManufacturerId = 8,
                            Name = "Radiator",
                            Price = 0.0
                        },
                        new
                        {
                            PartId = 17,
                            CarId = 2,
                            CategoryId = 2,
                            Description = "Stable suspension arms for Q5",
                            ManufacturerId = 1,
                            Name = "Control Arms",
                            Price = 0.0
                        },
                        new
                        {
                            PartId = 18,
                            CarId = 3,
                            CategoryId = 7,
                            Description = "Reliable ignition coil for Clio",
                            ManufacturerId = 2,
                            Name = "Ignition Coil",
                            Price = 0.0
                        },
                        new
                        {
                            PartId = 19,
                            CarId = 4,
                            CategoryId = 9,
                            Description = "Bright and durable headlights for 508",
                            ManufacturerId = 3,
                            Name = "Headlight Assembly",
                            Price = 0.0
                        },
                        new
                        {
                            PartId = 20,
                            CarId = 5,
                            CategoryId = 7,
                            Description = "Long-lasting battery for Panda",
                            ManufacturerId = 4,
                            Name = "Battery",
                            Price = 0.0
                        });
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<bool>("IsCard")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCash")
                        .HasColumnType("bit");

                    b.HasKey("PaymentId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            IsCard = true,
                            IsCash = false
                        },
                        new
                        {
                            PaymentId = 2,
                            IsCard = false,
                            IsCash = true
                        });
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Picture")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("PartId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusId");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            StatusId = 2,
                            Name = "Approved"
                        },
                        new
                        {
                            StatusId = 3,
                            Name = "Rejected"
                        },
                        new
                        {
                            StatusId = 4,
                            Name = "In Progress"
                        },
                        new
                        {
                            StatusId = 5,
                            Name = "Completed"
                        },
                        new
                        {
                            StatusId = 6,
                            Name = "Cancelled"
                        },
                        new
                        {
                            StatusId = 7,
                            Name = "On Hold"
                        },
                        new
                        {
                            StatusId = 8,
                            Name = "Failed"
                        },
                        new
                        {
                            StatusId = 9,
                            Name = "Draft"
                        },
                        new
                        {
                            StatusId = 10,
                            Name = "Submitted"
                        });
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierId = 1,
                            Address = "Maršala Tita 45, Sarajevo, BiH",
                            Contact = "+387 33 123 456",
                            Name = "A2B Delivery"
                        },
                        new
                        {
                            SupplierId = 2,
                            Address = "Kralja Petra I Karađorđevića 102, Banja Luka, BiH",
                            Contact = "+387 51 789 123",
                            Name = "EuroExpress"
                        },
                        new
                        {
                            SupplierId = 3,
                            Address = "Hamdije Kreševljakovića 50, Mostar, BiH",
                            Contact = "+387 61 987 654",
                            Name = "BH Brza Pošta"
                        },
                        new
                        {
                            SupplierId = 4,
                            Address = "Zagrebačka 10, Tuzla, BiH",
                            Contact = "+387 36 456 789",
                            Name = "Sky Express"
                        },
                        new
                        {
                            SupplierId = 5,
                            Address = "Bosanska 25, Zenica, BiH",
                            Contact = "+387 32 555 888",
                            Name = "Express One"
                        },
                        new
                        {
                            SupplierId = 6,
                            Address = "Srebrenička 7, Brčko, BiH",
                            Contact = "+387 35 222 333",
                            Name = "FastTrack Logistics"
                        },
                        new
                        {
                            SupplierId = 7,
                            Address = "Zmaja od Bosne 12, Sarajevo, BiH",
                            Contact = "+387 33 445 666",
                            Name = "DHL Bosnia"
                        },
                        new
                        {
                            SupplierId = 8,
                            Address = "Goranska 15, Bihać, BiH",
                            Contact = "+387 37 777 888",
                            Name = "GLS BiH"
                        },
                        new
                        {
                            SupplierId = 9,
                            Address = "Savska 4, Bijeljina, BiH",
                            Contact = "+387 66 123 321",
                            Name = "UPS Delivery"
                        },
                        new
                        {
                            SupplierId = 10,
                            Address = "Prijedorska 22, Prijedor, BiH",
                            Contact = "+387 65 999 000",
                            Name = "PostExpress BiH"
                        });
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is2FActive")
                        .HasColumnType("bit");

                    b.Property<bool>("isUser")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("UserAccounts");

                    b.HasDiscriminator().HasValue("UserAccount");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Admin", b =>
                {
                    b.HasBaseType("RS1_2024_25.API.Data.Models.UserAccount");

                    b.Property<string>("AdminLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Admin");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Masline-Kocine bb",
                            Email = "amar.kodro@edu.fit.ba",
                            IsAdmin = true,
                            Name = "Amar",
                            Password = "driveparts",
                            PhoneNumber = "0623331233",
                            Surname = "Kodro",
                            Username = "amar.kodro",
                            is2FActive = true,
                            isUser = false,
                            AdminLevel = "Moderator"
                        });
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.User", b =>
                {
                    b.HasBaseType("RS1_2024_25.API.Data.Models.UserAccount");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.HasIndex("CityId");

                    b.HasIndex("GenderId");

                    b.HasDiscriminator().HasValue("User");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Address = "useraddress",
                            Email = "testuser@example.com",
                            IsAdmin = false,
                            Name = "Test",
                            Password = "testuser123",
                            PhoneNumber = "0602213312",
                            Surname = "User",
                            Username = "TestUser1",
                            is2FActive = false,
                            isUser = true,
                            CityId = 18,
                            GenderId = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "useraddress2",
                            Email = "testuser2@example.com",
                            IsAdmin = false,
                            Name = "Test2",
                            Password = "testuser2",
                            PhoneNumber = "0602234312",
                            Surname = "User2",
                            Username = "TestUser2",
                            is2FActive = false,
                            isUser = true,
                            CityId = 16,
                            GenderId = 2
                        });
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Auth.MyAuthenticationToken", b =>
                {
                    b.HasOne("RS1_2024_25.API.Data.Models.Auth.MyAppUser", "MyAppUser")
                        .WithMany()
                        .HasForeignKey("MyAppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MyAppUser");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.CarEngine", b =>
                {
                    b.HasOne("RS1_2024_25.API.Data.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RS1_2024_25.API.Data.Models.Engine", "Engine")
                        .WithMany()
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Engine");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.City", b =>
                {
                    b.HasOne("RS1_2024_25.API.Data.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.FAQ", b =>
                {
                    b.HasOne("RS1_2024_25.API.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Journey", b =>
                {
                    b.HasOne("RS1_2024_25.API.Data.Models.City", "EndCity")
                        .WithMany()
                        .HasForeignKey("EndCityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RS1_2024_25.API.Data.Models.City", "StartCity")
                        .WithMany()
                        .HasForeignKey("StartCityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("EndCity");

                    b.Navigation("StartCity");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Order", b =>
                {
                    b.HasOne("RS1_2024_25.API.Data.Models.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RS1_2024_25.API.Data.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RS1_2024_25.API.Data.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RS1_2024_25.API.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Payment");

                    b.Navigation("Status");

                    b.Navigation("Supplier");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.OrderItem", b =>
                {
                    b.HasOne("RS1_2024_25.API.Data.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RS1_2024_25.API.Data.Models.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Part", b =>
                {
                    b.HasOne("RS1_2024_25.API.Data.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RS1_2024_25.API.Data.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RS1_2024_25.API.Data.Models.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Category");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Review", b =>
                {
                    b.HasOne("RS1_2024_25.API.Data.Models.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RS1_2024_25.API.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.User", b =>
                {
                    b.HasOne("RS1_2024_25.API.Data.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RS1_2024_25.API.Data.Models.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Gender");
                });
#pragma warning restore 612, 618
        }
    }
}
