// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RS1_2024_25.API.Data;

#nullable disable

namespace RS1_2024_25.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Auth.MyAppUser", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsManager")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("MyAppUsers");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Auth.MyAuthenticationToken", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MyAppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("MyAppUserId");

                    b.ToTable("MyAuthenticationTokens");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            CarId = 1,
                            Brand = "Volkswagen"
                        },
                        new
                        {
                            CarId = 2,
                            Brand = "Audi"
                        },
                        new
                        {
                            CarId = 3,
                            Brand = "Renault"
                        },
                        new
                        {
                            CarId = 4,
                            Brand = "Peugeot"
                        },
                        new
                        {
                            CarId = 5,
                            Brand = "Fiat"
                        },
                        new
                        {
                            CarId = 6,
                            Brand = "BMW"
                        },
                        new
                        {
                            CarId = 7,
                            Brand = "Mercedes"
                        },
                        new
                        {
                            CarId = 8,
                            Brand = "Tesla"
                        },
                        new
                        {
                            CarId = 9,
                            Brand = "Ford"
                        },
                        new
                        {
                            CarId = 10,
                            Brand = "Toyota"
                        },
                        new
                        {
                            CarId = 11,
                            Brand = "Honda"
                        },
                        new
                        {
                            CarId = 12,
                            Brand = "Nissan"
                        },
                        new
                        {
                            CarId = 13,
                            Brand = "Mazda"
                        },
                        new
                        {
                            CarId = 14,
                            Brand = "Kia"
                        },
                        new
                        {
                            CarId = 15,
                            Brand = "Hyundai"
                        },
                        new
                        {
                            CarId = 16,
                            Brand = "Chevrolet"
                        },
                        new
                        {
                            CarId = 17,
                            Brand = "Subaru"
                        },
                        new
                        {
                            CarId = 18,
                            Brand = "Jeep"
                        },
                        new
                        {
                            CarId = 19,
                            Brand = "Volvo"
                        });
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Brakes"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Suspension"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Engine Parts"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Exhaust Systems"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Oil and Fluids"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Filters"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Electrical Components"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Cooling Systems"
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "Interior Accessories"
                        },
                        new
                        {
                            CategoryId = 10,
                            Name = "Tires and Wheels"
                        },
                        new
                        {
                            CategoryId = 11,
                            Name = "Body Parts and Exterior"
                        },
                        new
                        {
                            CategoryId = 12,
                            Name = "Lighting Systems"
                        },
                        new
                        {
                            CategoryId = 13,
                            Name = "Transmission Parts"
                        },
                        new
                        {
                            CategoryId = 14,
                            Name = "Fuel System Components"
                        });
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.City", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CountryId = 1,
                            Name = "Banja Luka"
                        },
                        new
                        {
                            ID = 2,
                            CountryId = 1,
                            Name = "Bihać"
                        },
                        new
                        {
                            ID = 3,
                            CountryId = 1,
                            Name = "Bijeljina"
                        },
                        new
                        {
                            ID = 4,
                            CountryId = 1,
                            Name = "Bosanska Krupa"
                        },
                        new
                        {
                            ID = 5,
                            CountryId = 1,
                            Name = "Cazin"
                        },
                        new
                        {
                            ID = 6,
                            CountryId = 1,
                            Name = "Čapljina"
                        },
                        new
                        {
                            ID = 7,
                            CountryId = 1,
                            Name = "Drventa"
                        },
                        new
                        {
                            ID = 8,
                            CountryId = 1,
                            Name = "Doboj"
                        },
                        new
                        {
                            ID = 9,
                            CountryId = 1,
                            Name = "Goražde"
                        },
                        new
                        {
                            ID = 10,
                            CountryId = 1,
                            Name = "Gračanica"
                        },
                        new
                        {
                            ID = 11,
                            CountryId = 1,
                            Name = "Cityačac"
                        },
                        new
                        {
                            ID = 12,
                            CountryId = 1,
                            Name = "Cityiška"
                        },
                        new
                        {
                            ID = 13,
                            CountryId = 1,
                            Name = "Konjic"
                        },
                        new
                        {
                            ID = 14,
                            CountryId = 1,
                            Name = "Laktaši"
                        },
                        new
                        {
                            ID = 15,
                            CountryId = 1,
                            Name = "Livno"
                        },
                        new
                        {
                            ID = 16,
                            CountryId = 1,
                            Name = "Lukavac"
                        },
                        new
                        {
                            ID = 17,
                            CountryId = 1,
                            Name = "Ljubuški"
                        },
                        new
                        {
                            ID = 18,
                            CountryId = 1,
                            Name = "Mostar"
                        },
                        new
                        {
                            ID = 19,
                            CountryId = 1,
                            Name = "Orašje"
                        },
                        new
                        {
                            ID = 20,
                            CountryId = 1,
                            Name = "Prijedor"
                        },
                        new
                        {
                            ID = 21,
                            CountryId = 1,
                            Name = "Prnjavor"
                        },
                        new
                        {
                            ID = 22,
                            CountryId = 1,
                            Name = "Sarajevo"
                        },
                        new
                        {
                            ID = 23,
                            CountryId = 1,
                            Name = "Srebrenik"
                        },
                        new
                        {
                            ID = 24,
                            CountryId = 1,
                            Name = "Stolac"
                        },
                        new
                        {
                            ID = 25,
                            CountryId = 1,
                            Name = "Široki Brijeg"
                        },
                        new
                        {
                            ID = 26,
                            CountryId = 1,
                            Name = "Travnik"
                        },
                        new
                        {
                            ID = 27,
                            CountryId = 1,
                            Name = "Tuzla"
                        },
                        new
                        {
                            ID = 28,
                            CountryId = 1,
                            Name = "Visoko"
                        },
                        new
                        {
                            ID = 29,
                            CountryId = 1,
                            Name = "Zavidovići"
                        },
                        new
                        {
                            ID = 30,
                            CountryId = 1,
                            Name = "Zenica"
                        },
                        new
                        {
                            ID = 31,
                            CountryId = 1,
                            Name = "Zvornik"
                        },
                        new
                        {
                            ID = 32,
                            CountryId = 1,
                            Name = "Živinice"
                        },
                        new
                        {
                            ID = 33,
                            CountryId = 1,
                            Name = "Donji Vakuf"
                        },
                        new
                        {
                            ID = 34,
                            CountryId = 1,
                            Name = "Zavidovići"
                        });
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Country", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Bosna i Hercegovina"
                        });
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Engine", b =>
                {
                    b.Property<int>("EngineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EngineId"));

                    b.Property<double>("Displacement")
                        .HasColumnType("float");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.HasKey("EngineId");

                    b.ToTable("Engines");

                    b.HasData(
                        new
                        {
                            EngineId = 1,
                            Displacement = 2000.0,
                            FuelType = "Diesel",
                            Name = "TDI 2.0",
                            Power = 150
                        },
                        new
                        {
                            EngineId = 2,
                            Displacement = 1500.0,
                            FuelType = "Petrol",
                            Name = "TSI 1.5",
                            Power = 130
                        },
                        new
                        {
                            EngineId = 3,
                            Displacement = 0.0,
                            FuelType = "Electric",
                            Name = "Electric R100",
                            Power = 100
                        },
                        new
                        {
                            EngineId = 4,
                            Displacement = 1600.0,
                            FuelType = "Hybrid",
                            Name = "HY 1.6",
                            Power = 180
                        },
                        new
                        {
                            EngineId = 5,
                            Displacement = 1200.0,
                            FuelType = "Petrol",
                            Name = "FIAT Petrol 1.2",
                            Power = 90
                        },
                        new
                        {
                            EngineId = 6,
                            Displacement = 1600.0,
                            FuelType = "Diesel",
                            Name = "TDI 1.6",
                            Power = 120
                        },
                        new
                        {
                            EngineId = 7,
                            Displacement = 2000.0,
                            FuelType = "Petrol",
                            Name = "TSI 2.0",
                            Power = 200
                        },
                        new
                        {
                            EngineId = 8,
                            Displacement = 2000.0,
                            FuelType = "Hybrid",
                            Name = "Hybrid E-Drive",
                            Power = 250
                        },
                        new
                        {
                            EngineId = 9,
                            Displacement = 0.0,
                            FuelType = "Electric",
                            Name = "Electric P150",
                            Power = 150
                        },
                        new
                        {
                            EngineId = 10,
                            Displacement = 1000.0,
                            FuelType = "Petrol",
                            Name = "EcoBoost 1.0",
                            Power = 125
                        },
                        new
                        {
                            EngineId = 11,
                            Displacement = 1500.0,
                            FuelType = "Petrol",
                            Name = "VTEC 1.5",
                            Power = 180
                        },
                        new
                        {
                            EngineId = 12,
                            Displacement = 2500.0,
                            FuelType = "Petrol",
                            Name = "Skyactiv 2.5",
                            Power = 187
                        },
                        new
                        {
                            EngineId = 13,
                            Displacement = 1600.0,
                            FuelType = "Petrol",
                            Name = "GDi 1.6",
                            Power = 177
                        },
                        new
                        {
                            EngineId = 14,
                            Displacement = 5700.0,
                            FuelType = "Petrol",
                            Name = "Hemi 5.7",
                            Power = 395
                        },
                        new
                        {
                            EngineId = 15,
                            Displacement = 2000.0,
                            FuelType = "Petrol",
                            Name = "T6 2.0",
                            Power = 316
                        },
                        new
                        {
                            EngineId = 16,
                            Displacement = 3000.0,
                            FuelType = "Diesel",
                            Name = "3.0 TDI",
                            Power = 245
                        },
                        new
                        {
                            EngineId = 17,
                            Displacement = 3000.0,
                            FuelType = "Diesel",
                            Name = "N57D30O0",
                            Power = 241
                        },
                        new
                        {
                            EngineId = 18,
                            Displacement = 5500.0,
                            FuelType = "Petrol",
                            Name = "M157 V8",
                            Power = 577
                        });
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.FAQ", b =>
                {
                    b.Property<int>("FAQId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FAQId"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FAQId");

                    b.HasIndex("UserId");

                    b.ToTable("FAQs");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Gender", b =>
                {
                    b.Property<int>("GenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenderId"));

                    b.Property<string>("GenderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenderId");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            GenderId = 1,
                            GenderName = "Male"
                        },
                        new
                        {
                            GenderId = 2,
                            GenderName = "Female"
                        });
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Journey", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("EndCityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartCityId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("EndCityId");

                    b.HasIndex("StartCityId");

                    b.ToTable("Journeys");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Manufacturer", b =>
                {
                    b.Property<int>("ManufacturerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManufacturerId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ManufacturerId");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            ManufacturerId = 1,
                            Address = "Džemala Bijedića 185, Sarajevo, Bosna i Hercegovina",
                            Contact = "+387 33 770 100",
                            Name = "Bosch"
                        },
                        new
                        {
                            ManufacturerId = 2,
                            Address = "Karađorđeva 120, Banja Luka, Bosna i Hercegovina",
                            Contact = "+387 51 210 990",
                            Name = "Valeo"
                        },
                        new
                        {
                            ManufacturerId = 3,
                            Address = "Rudarska 33, Tuzla, Bosna i Hercegovina",
                            Contact = "+387 35 320 870",
                            Name = "Delphi Technologies"
                        },
                        new
                        {
                            ManufacturerId = 4,
                            Address = "Bišće polje bb, Mostar, Bosna i Hercegovina",
                            Contact = "+387 36 576 600",
                            Name = "Continental"
                        },
                        new
                        {
                            ManufacturerId = 5,
                            Address = "Industrijska zona bb, Zenica, Bosna i Hercegovina",
                            Contact = "+387 32 450 110",
                            Name = "Magneti Marelli"
                        },
                        new
                        {
                            ManufacturerId = 6,
                            Address = "Pofalići bb, Sarajevo, Bosna i Hercegovina",
                            Contact = "+387 33 210 320",
                            Name = "Brembo"
                        },
                        new
                        {
                            ManufacturerId = 7,
                            Address = "Aleja Svetog Save 15, Banja Luka, Bosna i Hercegovina",
                            Contact = "+387 51 321 480",
                            Name = "TRW Automotive"
                        },
                        new
                        {
                            ManufacturerId = 8,
                            Address = "Zmaja od Bosne bb, Sarajevo, Bosna i Hercegovina",
                            Contact = "+387 33 234 567",
                            Name = "ATE"
                        });
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Model", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModelId"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("EngineId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ModelId");

                    b.HasIndex("CarId");

                    b.HasIndex("EngineId");

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            ModelId = 1,
                            CarId = 4,
                            EngineId = 1,
                            Name = "508",
                            Year = 2020
                        },
                        new
                        {
                            ModelId = 2,
                            CarId = 5,
                            EngineId = 2,
                            Name = "Panda",
                            Year = 2019
                        },
                        new
                        {
                            ModelId = 3,
                            CarId = 1,
                            EngineId = 3,
                            Name = "Tiguan",
                            Year = 2022
                        },
                        new
                        {
                            ModelId = 4,
                            CarId = 1,
                            EngineId = 4,
                            Name = "Passat",
                            Year = 2021
                        },
                        new
                        {
                            ModelId = 5,
                            CarId = 1,
                            EngineId = 5,
                            Name = "Golf 8",
                            Year = 2023
                        },
                        new
                        {
                            ModelId = 6,
                            CarId = 1,
                            EngineId = 6,
                            Name = "Golf 7",
                            Year = 2020
                        },
                        new
                        {
                            ModelId = 7,
                            CarId = 6,
                            EngineId = 7,
                            Name = "X5",
                            Year = 2022
                        },
                        new
                        {
                            ModelId = 8,
                            CarId = 6,
                            EngineId = 8,
                            Name = "3 Series",
                            Year = 2021
                        },
                        new
                        {
                            ModelId = 9,
                            CarId = 7,
                            EngineId = 9,
                            Name = "C-Class",
                            Year = 2023
                        },
                        new
                        {
                            ModelId = 10,
                            CarId = 7,
                            EngineId = 10,
                            Name = "GLE",
                            Year = 2022
                        },
                        new
                        {
                            ModelId = 11,
                            CarId = 8,
                            EngineId = 11,
                            Name = "Model S",
                            Year = 2023
                        },
                        new
                        {
                            ModelId = 12,
                            CarId = 9,
                            EngineId = 12,
                            Name = "Focus",
                            Year = 2021
                        },
                        new
                        {
                            ModelId = 13,
                            CarId = 10,
                            EngineId = 13,
                            Name = "Corolla",
                            Year = 2020
                        },
                        new
                        {
                            ModelId = 14,
                            CarId = 11,
                            EngineId = 14,
                            Name = "Civic",
                            Year = 2022
                        },
                        new
                        {
                            ModelId = 15,
                            CarId = 12,
                            EngineId = 15,
                            Name = "Altima",
                            Year = 2021
                        },
                        new
                        {
                            ModelId = 16,
                            CarId = 13,
                            EngineId = 10,
                            Name = "CX-5",
                            Year = 2023
                        },
                        new
                        {
                            ModelId = 17,
                            CarId = 6,
                            EngineId = 17,
                            Name = "5 series",
                            Year = 2014
                        },
                        new
                        {
                            ModelId = 18,
                            CarId = 4,
                            EngineId = 13,
                            Name = "308",
                            Year = 2008
                        },
                        new
                        {
                            ModelId = 19,
                            CarId = 7,
                            EngineId = 18,
                            Name = "S63",
                            Year = 2020
                        },
                        new
                        {
                            ModelId = 20,
                            CarId = 2,
                            EngineId = 16,
                            Name = "A6",
                            Year = 2013
                        },
                        new
                        {
                            ModelId = 21,
                            CarId = 6,
                            EngineId = 17,
                            Name = "7 series",
                            Year = 2013
                        });
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.ModelPart", b =>
                {
                    b.Property<int>("ModelPartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModelPartId"));

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.HasKey("ModelPartId");

                    b.HasIndex("ModelId");

                    b.HasIndex("PartId");

                    b.ToTable("ModelParts");

                    b.HasData(
                        new
                        {
                            ModelPartId = 1,
                            ModelId = 1,
                            PartId = 4
                        },
                        new
                        {
                            ModelPartId = 2,
                            ModelId = 1,
                            PartId = 17
                        },
                        new
                        {
                            ModelPartId = 3,
                            ModelId = 2,
                            PartId = 3
                        },
                        new
                        {
                            ModelPartId = 4,
                            ModelId = 2,
                            PartId = 6
                        },
                        new
                        {
                            ModelPartId = 5,
                            ModelId = 3,
                            PartId = 23
                        },
                        new
                        {
                            ModelPartId = 6,
                            ModelId = 4,
                            PartId = 5
                        },
                        new
                        {
                            ModelPartId = 8,
                            ModelId = 6,
                            PartId = 19
                        },
                        new
                        {
                            ModelPartId = 9,
                            ModelId = 7,
                            PartId = 15
                        },
                        new
                        {
                            ModelPartId = 10,
                            ModelId = 9,
                            PartId = 12
                        },
                        new
                        {
                            ModelPartId = 11,
                            ModelId = 4,
                            PartId = 25
                        },
                        new
                        {
                            ModelPartId = 12,
                            ModelId = 3,
                            PartId = 2
                        },
                        new
                        {
                            ModelPartId = 13,
                            ModelId = 14,
                            PartId = 16
                        },
                        new
                        {
                            ModelPartId = 14,
                            ModelId = 13,
                            PartId = 22
                        },
                        new
                        {
                            ModelPartId = 15,
                            ModelId = 15,
                            PartId = 21
                        },
                        new
                        {
                            ModelPartId = 16,
                            ModelId = 17,
                            PartId = 26
                        },
                        new
                        {
                            ModelPartId = 17,
                            ModelId = 17,
                            PartId = 33
                        },
                        new
                        {
                            ModelPartId = 18,
                            ModelId = 18,
                            PartId = 27
                        },
                        new
                        {
                            ModelPartId = 19,
                            ModelId = 19,
                            PartId = 28
                        },
                        new
                        {
                            ModelPartId = 20,
                            ModelId = 20,
                            PartId = 29
                        },
                        new
                        {
                            ModelPartId = 21,
                            ModelId = 21,
                            PartId = 30
                        },
                        new
                        {
                            ModelPartId = 22,
                            ModelId = 3,
                            PartId = 31
                        },
                        new
                        {
                            ModelPartId = 23,
                            ModelId = 4,
                            PartId = 32
                        },
                        new
                        {
                            ModelPartId = 24,
                            ModelId = 10,
                            PartId = 34
                        },
                        new
                        {
                            ModelPartId = 25,
                            ModelId = 8,
                            PartId = 35
                        });
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("StatusId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PartId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Part", b =>
                {
                    b.Property<int>("PartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNewArrival")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("bit");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("PartId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("TypeId");

                    b.ToTable("Parts");

                    b.HasData(
                        new
                        {
                            PartId = 1,
                            CategoryId = 1,
                            Description = "High-quality brake pads for Golf",
                            IsFeatured = true,
                            IsNewArrival = false,
                            IsOnSale = false,
                            ManufacturerId = 1,
                            Name = "Brake Pads",
                            PartImage = "/images/BOSCH_brake_pads.jpg",
                            Price = 85.0
                        },
                        new
                        {
                            PartId = 2,
                            CategoryId = 2,
                            Description = "Durable suspension springs for Q5,Tiguan",
                            IsFeatured = true,
                            IsNewArrival = false,
                            IsOnSale = false,
                            ManufacturerId = 2,
                            Name = "Suspension Springs",
                            PartImage = "/images/Suspension_Springs_q5.jpg",
                            Price = 220.0
                        },
                        new
                        {
                            PartId = 3,
                            CategoryId = 6,
                            Description = "Oil filter suitable for Clio engines",
                            IsFeatured = true,
                            IsNewArrival = false,
                            IsOnSale = false,
                            ManufacturerId = 3,
                            Name = "Engine Oil Filter",
                            PartImage = "/images/oil_filter_renault_clio.jpg",
                            Price = 25.0
                        },
                        new
                        {
                            PartId = 4,
                            CategoryId = 4,
                            Description = "Rust-resistant exhaust pipe for 508",
                            IsFeatured = true,
                            IsNewArrival = false,
                            IsOnSale = false,
                            ManufacturerId = 4,
                            Name = "Exhaust Pipe",
                            PartImage = "/images/Exhaust_Pipe peugeot_508.jpg",
                            Price = 300.0,
                            TypeId = 1
                        },
                        new
                        {
                            PartId = 5,
                            CategoryId = 3,
                            Description = "Durable timing belt for Golf",
                            IsFeatured = true,
                            IsNewArrival = false,
                            IsOnSale = false,
                            ManufacturerId = 5,
                            Name = "Timing Belt",
                            PartImage = "/images/Timing_Belt_gol_VI.jpg",
                            Price = 120.0
                        },
                        new
                        {
                            PartId = 6,
                            CategoryId = 8,
                            Description = "High-efficiency water pump for Panda",
                            IsFeatured = true,
                            IsNewArrival = false,
                            IsOnSale = false,
                            ManufacturerId = 6,
                            Name = "Water Pump",
                            PartImage = "/images/Water_Pump_panda.jpg",
                            Price = 200.0
                        },
                        new
                        {
                            PartId = 7,
                            CategoryId = 3,
                            Description = "Precision camshaft for Q5",
                            IsFeatured = true,
                            IsNewArrival = false,
                            IsOnSale = false,
                            ManufacturerId = 7,
                            Name = "Camshaft",
                            PartImage = "/images/Camshaft_q5.jpg",
                            Price = 500.0
                        },
                        new
                        {
                            PartId = 8,
                            CategoryId = 7,
                            Description = "Reliable starter motor for Clio",
                            IsFeatured = true,
                            IsNewArrival = false,
                            IsOnSale = false,
                            ManufacturerId = 8,
                            Name = "Starter Motor",
                            PartImage = "/images/Starter_Motor_clio.jpg",
                            Price = 250.0
                        },
                        new
                        {
                            PartId = 9,
                            CategoryId = 8,
                            Description = "High-performance coolant hose for Panda",
                            IsFeatured = false,
                            IsNewArrival = true,
                            IsOnSale = false,
                            ManufacturerId = 5,
                            Name = "Coolant Hose",
                            PartImage = "/images/Coolant_Hose_panda.jpg",
                            Price = 40.0
                        },
                        new
                        {
                            PartId = 10,
                            CategoryId = 6,
                            Description = "Improves air intake efficiency for Golf",
                            IsFeatured = false,
                            IsNewArrival = true,
                            IsOnSale = false,
                            ManufacturerId = 6,
                            Name = "Air Filter",
                            PartImage = "/images/Air_Filter_golf_6.jpg",
                            Price = 35.0
                        },
                        new
                        {
                            PartId = 11,
                            CategoryId = 2,
                            Description = "Enhanced suspension system for Q5",
                            IsFeatured = false,
                            IsNewArrival = true,
                            IsOnSale = false,
                            ManufacturerId = 7,
                            Name = "Shock Absorber",
                            PartImage = "/images/Shock_Absorber_q5.jpg",
                            Price = 250.0
                        },
                        new
                        {
                            PartId = 12,
                            CategoryId = 7,
                            Description = "High-performance spark plugs for Clio",
                            IsFeatured = false,
                            IsNewArrival = true,
                            IsOnSale = false,
                            ManufacturerId = 8,
                            Name = "Spark Plugs",
                            PartImage = "/images/spark_plugs_clio.jpg",
                            Price = 50.0
                        },
                        new
                        {
                            PartId = 13,
                            CategoryId = 1,
                            Description = "Flexible brake hoses for Panda",
                            IsFeatured = false,
                            IsNewArrival = true,
                            IsOnSale = false,
                            ManufacturerId = 5,
                            Name = "Brake Hoses",
                            PartImage = "/images/brake_hoses_panda.jpg",
                            Price = 60.0
                        },
                        new
                        {
                            PartId = 14,
                            CategoryId = 8,
                            Description = "Pressure-regulating radiator cap for Golf",
                            IsFeatured = false,
                            IsNewArrival = true,
                            IsOnSale = false,
                            ManufacturerId = 6,
                            Name = "Radiator Cap",
                            PartImage = "/images/radiator_cap_golVI.jpg",
                            Price = 20.0
                        },
                        new
                        {
                            PartId = 15,
                            CategoryId = 2,
                            Description = "Precision wheel bearings for Q5",
                            IsFeatured = false,
                            IsNewArrival = true,
                            IsOnSale = false,
                            ManufacturerId = 7,
                            Name = "Wheel Bearings",
                            PartImage = "/images/wheel_bearings_q5.jpg",
                            Price = 100.0
                        },
                        new
                        {
                            PartId = 16,
                            CategoryId = 5,
                            Description = "Complete clutch kit for Clio",
                            IsFeatured = false,
                            IsNewArrival = true,
                            IsOnSale = false,
                            ManufacturerId = 8,
                            Name = "Clutch Kit",
                            PartImage = "/images/clutch_kit_clio.jpg",
                            Price = 300.0
                        },
                        new
                        {
                            PartId = 17,
                            CategoryId = 4,
                            Description = "Eco-friendly exhaust component for 508",
                            IsFeatured = false,
                            IsNewArrival = false,
                            IsOnSale = true,
                            ManufacturerId = 1,
                            Name = "Catalytic Converter",
                            PartImage = "/images/catalytic_converter_508.jpg",
                            Price = 450.0,
                            TypeId = 2
                        },
                        new
                        {
                            PartId = 18,
                            CategoryId = 5,
                            Description = "Premium oil for Panda engines",
                            IsFeatured = false,
                            IsNewArrival = false,
                            IsOnSale = true,
                            ManufacturerId = 2,
                            Name = "Engine Oil",
                            PartImage = "/images/engine_oil_panda.jpg",
                            Price = 90.0
                        },
                        new
                        {
                            PartId = 19,
                            CategoryId = 1,
                            Description = "Front brake discs for Golf",
                            IsFeatured = false,
                            IsNewArrival = false,
                            IsOnSale = true,
                            ManufacturerId = 3,
                            Name = "Brake Discs",
                            PartImage = "/images/brake_discs_golfVI.jpg",
                            Price = 150.0
                        },
                        new
                        {
                            PartId = 20,
                            CategoryId = 2,
                            Description = "Steering system component for Q5",
                            IsFeatured = false,
                            IsNewArrival = false,
                            IsOnSale = true,
                            ManufacturerId = 4,
                            Name = "Tie Rod Ends",
                            PartImage = "/images/tie_rod_ends_q5.jpg",
                            Price = 180.0
                        },
                        new
                        {
                            PartId = 21,
                            CategoryId = 4,
                            Description = "Durable exhaust manifold for Panda",
                            IsFeatured = false,
                            IsNewArrival = false,
                            IsOnSale = true,
                            ManufacturerId = 5,
                            Name = "Exhaust Manifold",
                            PartImage = "/images/exhaust_manifold_panda.jpg",
                            Price = 400.0
                        },
                        new
                        {
                            PartId = 22,
                            CategoryId = 3,
                            Description = "High-performance fuel injector for Golf",
                            IsFeatured = false,
                            IsNewArrival = false,
                            IsOnSale = true,
                            ManufacturerId = 6,
                            Name = "Fuel Injector",
                            PartImage = "/images/fuel_injector_golfVI.jpg",
                            Price = 250.0
                        },
                        new
                        {
                            PartId = 23,
                            CategoryId = 8,
                            Description = "Heat-resistant turbo hose for Q5,Tiguan",
                            IsFeatured = false,
                            IsNewArrival = false,
                            IsOnSale = true,
                            ManufacturerId = 7,
                            Name = "Turbo Hose",
                            PartImage = "/images/turbo_hose_q5.jpg",
                            Price = 80.0
                        },
                        new
                        {
                            PartId = 24,
                            CategoryId = 9,
                            Description = "Efficient AC compressor for Clio",
                            IsFeatured = false,
                            IsNewArrival = false,
                            IsOnSale = true,
                            ManufacturerId = 8,
                            Name = "Air Conditioning Compressor",
                            PartImage = "/images/air_conditioning_compressor_clio.jpg",
                            Price = 600.0
                        },
                        new
                        {
                            PartId = 25,
                            CategoryId = 11,
                            Description = "Stop light for Passat",
                            IsFeatured = false,
                            IsNewArrival = false,
                            IsOnSale = false,
                            ManufacturerId = 1,
                            Name = "Stop light",
                            PartImage = "/images/stoplight_passat.jpg",
                            Price = 150.0,
                            TypeId = 1
                        },
                        new
                        {
                            PartId = 26,
                            CategoryId = 7,
                            Description = "German made battery charging part F10",
                            IsFeatured = false,
                            IsNewArrival = false,
                            IsOnSale = false,
                            ManufacturerId = 1,
                            Name = "Alternator",
                            PartImage = "/images/Alternator_BMW.jpg",
                            Price = 350.0
                        },
                        new
                        {
                            PartId = 27,
                            CategoryId = 8,
                            Description = "High-quality cooling part for 308",
                            IsFeatured = false,
                            IsNewArrival = false,
                            IsOnSale = false,
                            ManufacturerId = 2,
                            Name = "Radiator",
                            PartImage = "/images/Radiator_308.jpg",
                            Price = 200.0
                        },
                        new
                        {
                            PartId = 28,
                            CategoryId = 12,
                            Description = "Clear and blinding headlights for S63",
                            IsFeatured = false,
                            IsNewArrival = false,
                            IsOnSale = false,
                            ManufacturerId = 1,
                            Name = "Headlights",
                            PartImage = "/images/Headlight_S63.jpg",
                            Price = 320.0
                        },
                        new
                        {
                            PartId = 29,
                            CategoryId = 12,
                            Description = "LED tailights,highly visible for A6",
                            IsFeatured = false,
                            IsNewArrival = false,
                            IsOnSale = false,
                            ManufacturerId = 2,
                            Name = "Taillights",
                            PartImage = "/images/Taillights-A6.jpg",
                            Price = 100.0,
                            TypeId = 1
                        },
                        new
                        {
                            PartId = 30,
                            CategoryId = 7,
                            Description = "Long lasting battery with start-stop system for BMW 7-series",
                            IsFeatured = false,
                            IsNewArrival = false,
                            IsOnSale = false,
                            ManufacturerId = 1,
                            Name = "Car Battery",
                            PartImage = "/images/Battery_BMW.jpg",
                            Price = 280.0
                        },
                        new
                        {
                            PartId = 31,
                            CategoryId = 11,
                            Description = "Smooth and high quality wipers for Tiguan",
                            IsFeatured = false,
                            IsNewArrival = false,
                            IsOnSale = false,
                            ManufacturerId = 4,
                            Name = "Windshield Wipers",
                            PartImage = "/images/Wipers_VW.jpg",
                            Price = 54.0
                        },
                        new
                        {
                            PartId = 32,
                            CategoryId = 5,
                            Description = "Durable pump for Passat",
                            IsFeatured = false,
                            IsNewArrival = false,
                            IsOnSale = false,
                            ManufacturerId = 2,
                            Name = "Oil Pump",
                            PartImage = "/images/OilPump_Passat.jpg",
                            Price = 140.0
                        },
                        new
                        {
                            PartId = 33,
                            CategoryId = 14,
                            Description = "Pump with filter for F10",
                            IsFeatured = false,
                            IsNewArrival = false,
                            IsOnSale = false,
                            ManufacturerId = 2,
                            Name = "Fuel Pump",
                            PartImage = "/images/FuelPump_BMW.jpg",
                            Price = 170.0
                        },
                        new
                        {
                            PartId = 34,
                            CategoryId = 9,
                            Description = "Dashboard with sun protection for GLE",
                            IsFeatured = false,
                            IsNewArrival = false,
                            IsOnSale = false,
                            ManufacturerId = 3,
                            Name = "Dashboard",
                            PartImage = "/images/DashBoard_Mercedes.jpg",
                            Price = 480.0
                        },
                        new
                        {
                            PartId = 35,
                            CategoryId = 9,
                            Description = "M-Performance Steering wheel for 3 series",
                            IsFeatured = false,
                            IsNewArrival = false,
                            IsOnSale = false,
                            ManufacturerId = 8,
                            Name = "Steering Wheel",
                            PartImage = "/images/SteeringWheel_3S.jpg",
                            Price = 220.0
                        });
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.PartEngine", b =>
                {
                    b.Property<int>("PartEngineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartEngineId"));

                    b.Property<int>("EngineId")
                        .HasColumnType("int");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.HasKey("PartEngineId");

                    b.HasIndex("EngineId");

                    b.HasIndex("PartId");

                    b.ToTable("PartEngines");

                    b.HasData(
                        new
                        {
                            PartEngineId = 1,
                            EngineId = 4,
                            PartId = 3
                        },
                        new
                        {
                            PartEngineId = 2,
                            EngineId = 12,
                            PartId = 4
                        },
                        new
                        {
                            PartEngineId = 3,
                            EngineId = 6,
                            PartId = 5
                        },
                        new
                        {
                            PartEngineId = 4,
                            EngineId = 5,
                            PartId = 6
                        },
                        new
                        {
                            PartEngineId = 5,
                            EngineId = 13,
                            PartId = 7
                        },
                        new
                        {
                            PartEngineId = 6,
                            EngineId = 9,
                            PartId = 8
                        },
                        new
                        {
                            PartEngineId = 7,
                            EngineId = 5,
                            PartId = 9
                        },
                        new
                        {
                            PartEngineId = 8,
                            EngineId = 1,
                            PartId = 10
                        },
                        new
                        {
                            PartEngineId = 9,
                            EngineId = 6,
                            PartId = 22
                        },
                        new
                        {
                            PartEngineId = 10,
                            EngineId = 7,
                            PartId = 23
                        },
                        new
                        {
                            PartEngineId = 11,
                            EngineId = 13,
                            PartId = 24
                        },
                        new
                        {
                            PartEngineId = 12,
                            EngineId = 17,
                            PartId = 26
                        },
                        new
                        {
                            PartEngineId = 13,
                            EngineId = 13,
                            PartId = 27
                        },
                        new
                        {
                            PartEngineId = 14,
                            EngineId = 1,
                            PartId = 32
                        },
                        new
                        {
                            PartEngineId = 15,
                            EngineId = 17,
                            PartId = 33
                        });
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            PaymentMethod = "Card"
                        },
                        new
                        {
                            PaymentId = 2,
                            PaymentMethod = "Cash"
                        });
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Picture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("PartId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusId");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            StatusId = 2,
                            Name = "Approved"
                        },
                        new
                        {
                            StatusId = 3,
                            Name = "Rejected"
                        },
                        new
                        {
                            StatusId = 4,
                            Name = "In Progress"
                        },
                        new
                        {
                            StatusId = 5,
                            Name = "Completed"
                        },
                        new
                        {
                            StatusId = 6,
                            Name = "Cancelled"
                        },
                        new
                        {
                            StatusId = 7,
                            Name = "On Hold"
                        },
                        new
                        {
                            StatusId = 8,
                            Name = "Failed"
                        },
                        new
                        {
                            StatusId = 9,
                            Name = "Draft"
                        },
                        new
                        {
                            StatusId = 10,
                            Name = "Submitted"
                        });
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierId = 1,
                            Address = "Maršala Tita 45, Sarajevo, BiH",
                            Contact = "+387 33 123 456",
                            Name = "A2B Delivery"
                        },
                        new
                        {
                            SupplierId = 2,
                            Address = "Kralja Petra I Karađorđevića 102, Banja Luka, BiH",
                            Contact = "+387 51 789 123",
                            Name = "EuroExpress"
                        },
                        new
                        {
                            SupplierId = 3,
                            Address = "Hamdije Kreševljakovića 50, Mostar, BiH",
                            Contact = "+387 61 987 654",
                            Name = "BH Brza Pošta"
                        },
                        new
                        {
                            SupplierId = 4,
                            Address = "Zagrebačka 10, Tuzla, BiH",
                            Contact = "+387 36 456 789",
                            Name = "Sky Express"
                        },
                        new
                        {
                            SupplierId = 5,
                            Address = "Bosanska 25, Zenica, BiH",
                            Contact = "+387 32 555 888",
                            Name = "Express One"
                        },
                        new
                        {
                            SupplierId = 6,
                            Address = "Srebrenička 7, Brčko, BiH",
                            Contact = "+387 35 222 333",
                            Name = "FastTrack Logistics"
                        },
                        new
                        {
                            SupplierId = 7,
                            Address = "Zmaja od Bosne 12, Sarajevo, BiH",
                            Contact = "+387 33 445 666",
                            Name = "DHL Bosnia"
                        },
                        new
                        {
                            SupplierId = 8,
                            Address = "Goranska 15, Bihać, BiH",
                            Contact = "+387 37 777 888",
                            Name = "GLS BiH"
                        },
                        new
                        {
                            SupplierId = 9,
                            Address = "Savska 4, Bijeljina, BiH",
                            Contact = "+387 66 123 321",
                            Name = "UPS Delivery"
                        },
                        new
                        {
                            SupplierId = 10,
                            Address = "Prijedorska 22, Prijedor, BiH",
                            Contact = "+387 65 999 000",
                            Name = "PostExpress BiH"
                        });
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Types", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeId");

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            TypeId = 1,
                            Name = "Sedan"
                        },
                        new
                        {
                            TypeId = 2,
                            Name = "Compact"
                        },
                        new
                        {
                            TypeId = 3,
                            Name = "SUV"
                        },
                        new
                        {
                            TypeId = 4,
                            Name = "Hatchback"
                        });
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("is2FActive")
                        .HasColumnType("bit");

                    b.Property<bool>("isUser")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("UserAccounts");

                    b.HasDiscriminator().HasValue("UserAccount");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Admin", b =>
                {
                    b.HasBaseType("RS1_2024_25.API.Data.Models.UserAccount");

                    b.Property<string>("AdminLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.User", b =>
                {
                    b.HasBaseType("RS1_2024_25.API.Data.Models.UserAccount");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<int?>("GenderId")
                        .HasColumnType("int");

                    b.HasIndex("CityId");

                    b.HasIndex("GenderId");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Auth.MyAuthenticationToken", b =>
                {
                    b.HasOne("RS1_2024_25.API.Data.Models.Auth.MyAppUser", "MyAppUser")
                        .WithMany()
                        .HasForeignKey("MyAppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MyAppUser");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.CartItem", b =>
                {
                    b.HasOne("RS1_2024_25.API.Data.Models.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RS1_2024_25.API.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.City", b =>
                {
                    b.HasOne("RS1_2024_25.API.Data.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.FAQ", b =>
                {
                    b.HasOne("RS1_2024_25.API.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Journey", b =>
                {
                    b.HasOne("RS1_2024_25.API.Data.Models.City", "EndCity")
                        .WithMany()
                        .HasForeignKey("EndCityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RS1_2024_25.API.Data.Models.City", "StartCity")
                        .WithMany()
                        .HasForeignKey("StartCityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("EndCity");

                    b.Navigation("StartCity");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Model", b =>
                {
                    b.HasOne("RS1_2024_25.API.Data.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RS1_2024_25.API.Data.Models.Engine", "Engine")
                        .WithMany()
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Engine");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.ModelPart", b =>
                {
                    b.HasOne("RS1_2024_25.API.Data.Models.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RS1_2024_25.API.Data.Models.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Order", b =>
                {
                    b.HasOne("RS1_2024_25.API.Data.Models.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RS1_2024_25.API.Data.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RS1_2024_25.API.Data.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RS1_2024_25.API.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Payment");

                    b.Navigation("Status");

                    b.Navigation("Supplier");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.OrderItem", b =>
                {
                    b.HasOne("RS1_2024_25.API.Data.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RS1_2024_25.API.Data.Models.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Part", b =>
                {
                    b.HasOne("RS1_2024_25.API.Data.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RS1_2024_25.API.Data.Models.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RS1_2024_25.API.Data.Models.Types", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");

                    b.Navigation("Manufacturer");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.PartEngine", b =>
                {
                    b.HasOne("RS1_2024_25.API.Data.Models.Engine", "Engine")
                        .WithMany()
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RS1_2024_25.API.Data.Models.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Engine");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.Review", b =>
                {
                    b.HasOne("RS1_2024_25.API.Data.Models.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RS1_2024_25.API.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RS1_2024_25.API.Data.Models.User", b =>
                {
                    b.HasOne("RS1_2024_25.API.Data.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("RS1_2024_25.API.Data.Models.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("City");

                    b.Navigation("Gender");
                });
#pragma warning restore 612, 618
        }
    }
}
